import { format } from 'date-fns';
import { Offer } from '../../types';
import { ELEVATOR_TYPES, MACHINE_TYPES, CONTROL_BOARDS, BATTERIES, VVVFS, RAILS } from './offerConstants';

export const createDefaultOffer = (): Partial<Offer> => ({
  customerName:        '',
  phone:               '',
  address:             '',
  locationUrl:         '',
  date:                format(new Date(), 'yyyy-MM-dd'),
  customerType:        'عميل',
  elevatorType:        ELEVATOR_TYPES[0],
  elevatorCount:       1,
  stops:               0,
  floors:              0,
  entrances:           1,
  load:                '',
  machineType:         MACHINE_TYPES[0],
  controlBoard:        CONTROL_BOARDS[0],
  battery:             BATTERIES[0],
  vvvf:                VVVFS[0],
  payment1:            0,
  payment2:            0,
  payment3:            0,
  payment4:            0,
  doorType:            '',
  innerDoor:           '',
  doorSize:            0,
  pitWidth:            0,
  lastFloorHeight:     0,
  pitDepth:            0,
  pitLength:           0,
  counterweightPosition: '',
  cabinSize:           '',
  price:               0,
  note1:               '',
  note2:               '',
  note3:               '',
  representative:      '',
  engNotes1:           '',
  engNotes2:           '',
  oldElevatorRemoval:  'لا يوجد',
  rails:               RAILS[0],
});
